import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kodigo Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ 
          background:"linear-gradient(0deg,rgba(0, 0, 0, 1) 0%, rgba(59, 48, 28, 1) 100%)",
          backgroundRepeat: "no-repeat",
          backgroundSize:  "cover",
          backgroundAttachment: "fixed",
          }}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
